# ========================================
# OPENAPI
# ========================================
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/docs

# ========================================
# DATASOURCE
# ========================================
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}
#------------------------------------------------
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=${DB_USERNAME}
%dev.quarkus.datasource.password=${DB_PASSWORD}
%dev.quarkus.datasource.jdbc.url=${DB_URL}
#------------------------------------------------

# ========================================
# HIBERNATE ORM
# ========================================
quarkus.hibernate-orm.packages=com.eliasmeyer.sp.infrastructure.persistence
quarkus.hibernate-orm.schema-management.strategy=validate

# ========================================
# LIQUIBASE
# ========================================
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.validate-on-migrate=true
quarkus.liquibase.clean-at-start=false
quarkus.liquibase.change-log=db/changelog-master.yaml
quarkus.liquibase.default-schema-name=${DB_SCHEMA:liquibase}
quarkus.liquibase.liquibase-schema-name=${DB_SCHEMA:liquibase}

# ========================================
# LOG
# ========================================
%prod.quarkus.log.level=WARN
%prod.quarkus.log.console.enable=false
%prod.quarkus.log.file.enable=true
%prod.quarkus.log.file.path=logs/application.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
%prod.quarkus.log.category."com.eliasmeyer.sp".level=WARN
%prod.quarkus.log.category."org.hibernate".level=WARN
%prod.quarkus.log.category."io.quarkus".level=INFO
%prod.quarkus.log.console.enabled=false
%prod.quarkus.log.console.async.enable=false
%prod.quarkus.log.file.async.enable=true
%prod.quarkus.log.syslog.async.enable=true
#------------------------------------------------
%dev.quarkus.log.category."com.eliasmeyer.sp".level=INFO
%dev.quarkus.log.category."org.hibernate".level=INFO
%dev.quarkus.log.category."io.quarkus".level=INFO
%dev.quarkus.log.console.enabled=true
%dev.quarkus.log.console.async.enable=true
%dev.quarkus.log.file.async.enable=true
%dev.quarkus.log.syslog.async.enable=true

# ========================================
# REST CLIENT
# ========================================
autorizador-api/mp-rest/url=https://em-payment-simplified.free.beeceptor.com
autorizador-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
autorizador-api/mp-rest/connectTimeout=5000
autorizador-api/mp-rest/readTimeout=10000