databaseChangeLog:
  - include:
      file: 01-create-usuario.yaml
      relativeToChangelogFile: true
  - include:
      file: 02-create-carteira.yaml
      relativeToChangelogFile: true
  - include:
      file: 03-create-transferencia.yaml
      relativeToChangelogFile: true
  - include:
      file: 04-create-outbox_event.yaml
      relativeToChangelogFile: true